matrix:
  include:
    - os: linux
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-27.0.2
          - android-27
          - add-on
          - extra
          #- sys-img-armeabi-v7a-google_apis-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
        - unzip -qq gradle-3.5-bin.zip
        - export GRADLE_HOME=$PWD/gradle-3.5
        - export PATH=$GRADLE_HOME/bin:$PATH
        - git clone https://github.com/flutter/flutter.git -b beta		
      script:
        - yes | sdkmanager "platforms;android-27"
        - yes | sdkmanager "build-tools;27.0.2"
        - yes | sdkmanager "build-tools;26.0.2"
        #- ./flutter/bin/flutter doctor --android-licenses
        - ./flutter/bin/flutter -v build apk
cache:
  directories:
    - $HOME/.pub-cache