theme: jekyll-theme-architect
title: MetroTrans
show_downloads: "true"

github:
  zip_url: https://github.com/aleguerra05/metro_trans/releases/download/0.6-beta/app-release.apk
  another_url: https://github.com/aleguerra05/metro_trans/releases/download/0.6-beta/app-release.apk
